/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "login": [],
    "dashboard.index": [],
    "dashboard.upload": [],
    "dashboard.upload.upload-photo": [],
    "dashboard.upload.create": [],
    "dashboard.campaigns": [],
    "dashboard.campaigns.adSets": [],
    "dashboard.campaigns.ads": [],
    "campaigns.status.update": [],
    "adSets.status.update": [],
    "ads.status.update": [],
    "dashboard.settings": [],
    "dashboard.settings.account": [],
    "dashboard.settings.ad-accounts": [],
    "dashboard.settings.ad-account.general": [],
    "dashboard.settings.ad-account.advertising-identity": [],
    "select-ad-account": [],
    "logout": [],
    "reauthenticate": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
