/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "dashboard.index": [],
    "dashboard.campaigns": [],
    "dashboard.campaigns.adSets": [],
    "dashboard.campaigns.ads": [],
    "campaigns.status.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "adSets.status.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "ads.status.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
